/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnidemo_MainActivity */

#ifndef _Included_com_example_jnidemo_MainActivity
#define _Included_com_example_jnidemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#define LOGD(fmt, ...)   __android_log_print(ANDROID_LOG_INFO, "TAG", fmt, __VA_ARGS__)

/*
 * Class:     com_example_jnidemo_MainActivity
 * Method:    localRef500
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnidemo_MainActivity_localRef500
  (JNIEnv *, jclass);

/*
 * Class:     com_example_jnidemo_MainActivity
 * Method:    localRef512
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnidemo_MainActivity_localRef512
  (JNIEnv *, jclass);

/*
 * Class:     com_example_jnidemo_MainActivity
 * Method:    localRef256
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnidemo_MainActivity_localRef256
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
